# Generated by Django 5.0.4 on 2024-05-15 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('alumno_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('profesor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('rol', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoTerminal',
            fields=[
                ('tt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateField()),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TESCOM_MAIN.profesor')),
                ('trabajo_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TESCOM_MAIN.trabajoterminal')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miercoles'), ('JU', 'Jueves'), ('VI', 'Viernes')], max_length=2)),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TESCOM_MAIN.profesor')),
            ],
            options={
                'unique_together': {('profesor', 'dia_semana', 'horario_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Alumno_Trabajo_Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TESCOM_MAIN.alumno')),
                ('trabajo_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TESCOM_MAIN.trabajoterminal')),
            ],
            options={
                'unique_together': {('alumno_id', 'trabajo_terminal')},
            },
        ),
    ]
