# Generated by Django 5.0.4 on 2024-06-30 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TESCOM_MAIN', '0002_alumnotrabajoterminal_delete_alumno_trabajo_terminal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnotrabajoterminal',
            name='archivo',
        ),
        migrations.AddField(
            model_name='trabajoterminal',
            name='alumno',
            field=models.ForeignKey(default=2021630178, on_delete=django.db.models.deletion.CASCADE, to='TESCOM_MAIN.alumno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajoterminal',
            name='archivo',
            field=models.FileField(default='trabajos_terminales/Protocolo.pdf', upload_to='trabajos_terminales/'),
        ),
    ]
