# Generated by Django 5.0.4 on 2024-06-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TESCOM_MAIN', '0004_alter_trabajoterminal_tt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajoterminal',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
