# Generated by Django 5.0.4 on 2024-06-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TESCOM_MAIN', '0005_alter_trabajoterminal_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajoterminal',
            name='profesores',
            field=models.ManyToManyField(related_name='trabajos_terminales', to='TESCOM_MAIN.profesor'),
        ),
    ]
